apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::904827379241:role/eks-prod-ssm-pm-role
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-param-test
spec:
  serviceAccountName: test
  containers:
    - name: param-test
      image: 904827379241.dkr.ecr.us-east-1.amazonaws.com/aws-parameter-init-container:latest
      imagePullPolicy: Always